language: go

go:
  - "1.14"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"

stages:
  - name: Build
  - name: Lint
  - name: Test

jobs:
  include:
    - stage: "Build"
      name: "build"
      script: make build

    - stage: "Lint"
      name: "golangci-lint"
      script: make lint

    - stage: "Test"
      name: "unit tests"
      install: go mod download
      script: make test
